const express = require('express')
const router = express.Router()
const userRouter = require('./user')
const colorRouter = require('./color')
const categoryRouter = require('./category')
const colorDetailRouter = require('./colorDetail')
const orderRouter = require('./order')
const postRouter = require('./post')
const postCategoryRouter = require('./postCategory')
const productRouter = require('./product')
const productOrderRouter = require('./productOrder')
const promotionRouter = require('./promotion')
const userAddressRouter = require('./userAddress')
const voucherRouter = require('./voucher')
const statisticRouter = require('./statistic')

router.use('/users', userRouter)
router.use('/colors', colorRouter)
router.use('/color-detail', colorDetailRouter)
router.use('/categories', categoryRouter)
router.use('/orders', orderRouter)
router.use('/posts', postRouter)
router.use('/post-categories', postCategoryRouter)
router.use('/products', productRouter)
router.use('/product-order', productOrderRouter)
router.use('/promotions', promotionRouter)
router.use('/user-address', userAddressRouter)
router.use('/vouchers', voucherRouter)
router.use('/statistics', statisticRouter)

module.exports = router
